Update bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,19 +1,47 @@
 ---
 format_version: 1.1.0
-default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
+default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
 project_type: ios
 trigger_map:
-- push_branch: "*"
+- push_branch: '*'
   workflow: primary
-- pull_request_source_branch: "*"
+- pull_request_source_branch: '*'
   workflow: primary
 workflows:
+  audit-this-step:
+    before_run:
+    - primary
+    steps:
+    - script:
+        title: Audit current step
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            stepman audit --step-yml ./step.yml
   primary:
     steps:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@6: {}
     - cache-pull@2: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            echo "Hello World!"
+            echo "CKB"
+
+            # or run a script from your repository, like:
+            # bash ./path/to/script.sh
+            # not just bash, e.g.:
+            # ruby ./path/to/script.rb
     - script:
         title: Create temp folder
         inputs:
@@ -31,23 +59,26 @@ workflows:
             fi
 
             mkdir "${TEMP_FOLDER}"
-    - path::./:
+    - 'path::./':
         title: Step Test
         description: ''
         run_if: true
         inputs:
-        - aws_access_key: "$AWS_ACCESS_KEY_ID"
-        - aws_secret_access_key: "$AWS_SECRET_ACCESS_KEY"
-        - s3_bucket: "$AWS_BUCKET"
-        - s3_filepath: "$AWS_FILE_PATH"
-        - output_location: "./_tmp"
+        - aws_access_key: $AWS_ACCESS_KEY_ID
+        - aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
+        - s3_bucket: $AWS_BUCKET
+        - s3_filepath: $AWS_FILE_PATH
+        - output_location: ./_tmp
     - script:
         title: Check environment variable
         inputs:
-        - content: |-
+        - content: >-
             #!/bin/bash
+
             eval TEMP_FOLDER="$(pwd)/_tmp"
-            if [ "${TEMP_FOLDER}/${FILE_NAME}" = "${S3_DOWNLOAD_OUTPUT_PATH}" ]; then
+
+            if [ "${TEMP_FOLDER}/${FILE_NAME}" = "${S3_DOWNLOAD_OUTPUT_PATH}" ];
+            then
               echo "Output is correctly set to ${S3_DOWNLOAD_OUTPUT_PATH}"
             else
               echo "Bad output ${S3_DOWNLOAD_OUTPUT_PATH}"
@@ -75,51 +106,55 @@ workflows:
     - certificate-and-profile-installer@1: {}
     - recreate-user-schemes@1:
         inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
+        - project_path: $BITRISE_PROJECT_PATH
     - xcode-archive@4:
         inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-        - scheme: "$BITRISE_SCHEME"
-        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
+        - project_path: $BITRISE_PROJECT_PATH
+        - scheme: $BITRISE_SCHEME
+        - distribution_method: $BITRISE_DISTRIBUTION_METHOD
     - deploy-to-bitrise-io@2: {}
     - cache-push@2: {}
-  audit-this-step:
-    before_run:
-    - primary
-    steps:
-    - script:
-        title: Audit current step
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            stepman audit --step-yml ./step.yml
   share-this-step:
     envs:
-    - MY_STEPLIB_REPO_FORK_GIT_URL: git@github.com:FutureWorkshops/bitrise-steplib.git
+    - MY_STEPLIB_REPO_FORK_GIT_URL: 'git@github.com:FutureWorkshops/bitrise-steplib.git'
     - STEP_ID_IN_STEPLIB: s3-download
-    - STEP_GIT_VERION_TAG_TO_SHARE: "$STEP_GIT_VERION_TAG_TO_SHARE"
-    - STEP_GIT_CLONE_URL: https://github.com/FutureWorkshops/bitrise-step-s3-download.git
-    description: |-
+    - STEP_GIT_VERION_TAG_TO_SHARE: $STEP_GIT_VERION_TAG_TO_SHARE
+    - STEP_GIT_CLONE_URL: 'https://github.com/FutureWorkshops/bitrise-step-s3-download.git'
+    description: >-
       If this is the first time you try to share a Step you should
+
       first call: $ bitrise share
 
+
       This will print you a guide, and information about how Step sharing
+
       works. Please read it at least once!
 
+
       As noted in the Step sharing guide you'll have to fork the
+
       StepLib you want to share this step into. Once you're done with forking
+
       the repository you should set your own fork's git clone URL
+
       in the `.bitrise.secrets.yml` file, or here in the `envs` section,
+
       as the value of the `MY_STEPLIB_REPO_FORK_GIT_URL` environment.
 
+
       You're now ready to share this Step, just make sure that
+
       the `STEP_ID_IN_STEPLIB` and `STEP_GIT_VERION_TAG_TO_SHARE`
+
       environments are set to the desired values!
 
-      To share this Step into a StepLib you can just run: $ bitrise run share-this-step
+
+      To share this Step into a StepLib you can just run: $ bitrise run
+      share-this-step
+
 
       Once it finishes the only thing left is to actually create a Pull Request,
+
       the way described in the guide printed at the end of the process.
     before_run:
     - audit-this-step
@@ -134,10 +169,13 @@ workflows:
     - script:
         title: Create new step version
         inputs:
-        - content: |-
+        - content: >-
             #!/bin/bash
+
             set -ex
-            bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
+
+            bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag
+            ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
     - script:
         title: Finish process
         inputs:
